setup.py

Changed reqs declaration in setup.py to permit dependencies >= required version.

Permit compilation with reqs >= specified version

---

gitless/cli/pprint.py

Without the `errors='ignore'` flag on `str.encode()`, there seem to be errors when trying to output to environments that don't support unicode.
I believe this commit would fix the error brought up in [this issue](https://github.com/sdg-mit/gitless/issues/52).
This came up when I was trying to write a homebrew formula that would install gitless. Test cases in formulas don't seem to handle unicode output automatically.

fixed potential unicode encoding error

---

gitless/cli/gl.py

The `color.ui` setting can not only have boolean values, but also values
like `never`, `always` or `auto`. Hence the check for color needs to be
expanded, else if it is set to `auto` it would lead to an error like:
$ python gl.py -h
Traceback (most recent call last):
File "gl.py", line 10, in <module>
from gitless.cli import gl
File "/home/vmx/src/python/gitless/gitless/gitless/cli/gl.py", line 39, in <module>
colored.DISABLE_COLOR = not repo.config.get_bool('color.ui')
File "/usr/lib/python2.7/dist-packages/pygit2/config.py", line 199, in get_bool
check_error(err)
File "/usr/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
raise GitError(message)
_pygit2.GitError: Failed to parse 'auto' as a boolean value
This fixes #42.

The `color.ui` setting isn't a boolean

---

gitless/cli/commit_dialog.py
gitless/cli/helpers.py

These commands obtained from `~/.gitconfig` or `$EDITOR` may contain spaces and need to be treated accordingly.
Closes #64.

Treat pager and editor as commands with arguments

---

gitless/cli/commit_dialog.py

At least I am in the habit of removing the boilerplate text, just so
that I'm absolutely sure that the commit message won't contain
anything other than what I've written (e.g. if I accidentally deleted
a character or two from the boilerplate text).  Thus, the end of
the commit message may be reached before the separator is found.
Thanks for writing and maintaining Gitless!
G'luck,
Peter

Fix an infinite readline() loop.

---

gitless/cli/helpers.py

Also check for the PAGER environment variable.
Add the -f and -r arguments if the user-specified pager is "less", too.
Thanks for writing and maintaining Gitless!
G'luck,
Peter

Improve the invocation of the pager.

---

gitless/cli/gl_switch.py

fixes #128 
`./setup.py test` returns `Ran 111 tests in 351.188s`, then `OK` and then many of these:
```
Exception AttributeError: "'NoneType' object has no attribute 'git_remote_free'" in 
<bound method Remote.__del__ of <pygit2.remote.Remote object at 0x10b6a5850
>> ignored
````
I guess Travis will tell...

Make `switch` command a bit more helpful

---

gitless/cli/gl.py

```
>py "gl.py"
Gitless: a version control system built on top of Git.
More info, downloads and documentation at http://gitless.com
commands:
track               start tracking changes to files
untrack             stop tracking changes to files
status              show status of the repo
diff                show changes to files
commit              save changes to the local repository
branch              list, create, delete, or edit branches
tag                 list, create, or delete tags
checkout            checkout committed versions of files
merge               merge the divergent changes of one branch onto another
resolve             mark files with conflicts as resolved
fuse                fuse the divergent changes of a branch onto the current branch
remote              list, …
```

Print help for humans, fixes #124

---

.travis.yml

https://docs.travis-ci.com/user/languages/python/#PyPy-Support
Because current pypy 2.5.0 builds are too slow
https://travis-ci.org/sdg-mit/gitless/builds/213701497

Use newer PyPy

---

.travis.yml

Add Python 3.6 and remove 3.2

---

.appveyor.yml

Tests are failing, because only Python 2.7 is present in PATH

Fix AppVeyor - add Scripts to path for current Python

---

gitless/cli/helpers.py

Resolves #164 by removing the message altogether.
Rationale: This warning is given when a user follows the "happy path"; they've set up an upstream remote, and are using the basic invocation of `publish`:
```bash
$ gl publish
! No dst branch specified, using upstream branch XXX/YYY
```
As a general rule, we shouldn't **warn** the user that we're doing as they've instructed. And in this case, informational messages follow, so we don't need to do that here either. The right choice is to remove this message altogether.

Remove warning, "No dst branch specified, using upstream branch..."

---

gitless/core.py

A breaking change was made in pygit2 0.27.1: it now returns None
instead of raising a KeyError if the specified path is not in
a Git repository.

Handle pygit2.discover_repository() returning None.

---

.travis.yml

Also unify syntax for long command lines. This should fix build failure.
See https://forum.snapcraft.io/t/ant-and-others-fails-using-docker-image/7673

.travis.yml Run apt update before snapcraft

---

.travis.yml

I tried to figure out why builds are not running and somebody from
https://travis-ci.community/c/product hinted that invalid YAML can
bring those issues.
I run it through linter and found that asterisk needs to be escaped
or it will be treated as an alias, invalid alias in this case.
https://yaml.org/YAML_for_ruby.html#simple_alias_example
Also removed docker leftover from the previous commit.

Remove docker and fix YAML

---

snap/snapcraft.yaml

This might fix #201, because it makes `snapcraft` switch to newer packaging logic.

Build snap on a newer Ubuntu base

---

gitless/tests/test_e2e.py

Binary name in snap is now `gitless.gl` and to run e2e tests
with, the `sh` invocation syntax should be changed for dot
https://amoffat.github.io/sh/sections/faq.html#how-do-i-execute-a-program-with-a-special-character-in-its-name

Patch test_e2e.py for easier command override

---

gitless/cli/gl_init.py
gitless/core.py

Made it so that gl init now takes -o/--only and -e/--exclude commands to perform filtering actions on the branches. The -o flag takes preference over the -e flag; if both exist, only the -o flag will be considered. However, this decision is up for discussion/changes if needed.

Added the -o and -e flags for the gl init command.

---

gitless/cli/gl.py
gitless/cli/helpers.py
gitless/tests/test_core.py

Allow gitless to track, untrack and resolve on files that start with
.git EXCEPT for the very specific directory at the top level of the repo
.git. For example, `gl track .gitignore` is fine, `gl track .git/HEAD`
is not allowed. Another, `gl track .gitdir/some_file` is allowed, `gl
track .git` will not be allowed.
Fixes #178 .
Made changes to the path processor and wrote unit tests against the path processor. Factored argparser out to a function so unit testing is easier.
The only issue(?) with this approach is that there is no error messaging. Gitless will ALWAYS silently drop the paths and do nothing. Git fatals and reports on the first path if all the paths are under .git/, otherwise it will silently drop the paths under .git/.
E.g.
```
$ git add .git/HEAD
error: invalid path …
```

Enable commands on .gitignore

---

gitless/cli/gl.py

Without this, "gl diff" or "gl history" show raw ANSI codes.  This solution only works on Win10 but it's already something.  Partial fix of issue #121

The Windows console (Win10) needs to be told to accept ANSI color codes

---

gitless/cli/gl_branch.py
gitless/core.py

In response to open issue #137 , added new lookup_branches in core that does one fetch given all the branch names. This reduced the time of gl branch -r from ~15 seconds to about 2-3 seconds now.

Added lookup_branches in core to make gl branch -r faster

---

gitless/cli/gl_branch.py

In the code, we get the remote name and add it before the branch name if the -v flag is not used, as listall_branches() does not have the remote name, just the branch name. However, when the -v flag is used, lookupall_branches() does have the remote name with the branch, so we don't need to add anything. Let me know if this should/could be changed!

Better performance of gl branch -r 

---

gitless/cli/helpers.py
gitless/tests/test_core.py
gitless/tests/utils.py

Add a check for symlinks when we check if a path is a directory and treat the symlink as a normal
file. Gitless will NOT follow the symlinks, because it could pull in the .git/ directory, files
outside of the repository or, in the worst case, the entire filesystem. This follows the behavior of
git. Git will commit symlinks into the repository and recreate the links on filesystems that support
it when the file is downloaded.

Stop following symlinks 216

---

.travis.sh
requirements.txt
setup.py
snap/snapcraft.yaml

This PR updates required version of `libgit2` to 0.99 and `pygit` to `1.1.1`.
I briefly had a look at [breaking changes in pygit2 changelog](https://github.com/libgit2/pygit2/blob/v1.1.1/CHANGELOG.rst), and it seems none of them affects the project.
These changes are required to get updated `libgit2` on Homebrew: https://github.com/Homebrew/homebrew-core/pull/51095

Update libgit2 to 0.99

---

gitless.1

Would fix #8
Generated man page based on gitless's pretty good help instructions. This should improve discoverability and cause less confusion to users upon trying to find gitless' man pages.

Add mostly-autogenerated man page

---

gitless/cli/gl.py
requirements.txt
setup.py

Fixes #226
Implemented using [argcomplete](https://kislyuk.github.io/argcomplete/)
Still needs automated install procedure. Screenshots of the tab completion in use, activated manually (in my personal fish shell, but argcomplete supports bash, zsh, fish and tzsh):
Which shells do we want to support automatic installation for? And what is the right place to hook a shell script completion installation? Offer it as an option (something like gl --install-completions) or as part of the pip / pyinstaller installation? https://stackoverflow.com/questions/58075926/python-argcomplete-and-pyinstaller Here's some info related to the technical implementation of automatically installing argcomplete completion in a pyinstaller packaged python application. …

WIP: Add tab completion support with argcomplete

---

gitless/cli/gl_switch.py
gitless/core.py

Helps with #20, and potentially #134 by adding a `-mi` / `--move-ignored` flag to `gl switch`.
Tested on a repo with ~1GB of ignored files. `gl switch -mi <branch>` takes less than 10 seconds.

Add --move-ignored / -mi flag to "gl switch".

---

gitless/cli/gl.py

A typo crept into the code that causes gitless to malfunction (tested on pygit2 1.5.0, python 3.9.1). After this fix, everything works as expected.
```
$ gl init
✔ Local repo created
$ gl track PKGBUILD
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/gitless/cli/gl.py", line 40, in <module>
pprint.DISABLE_COLOR = not repo.config.get_bool('color.ui')
File "/usr/lib/python3.9/site-packages/pygit2/config.py", line 219, in get_bool
check_error(err)
File "/usr/lib/python3.9/site-packages/pygit2/errors.py", line 65, in check_error
raise GitError(message)
_pygit2.GitError: failed to parse 'auto' as a boolean value
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/bin/gl", line 33, in <module> …
```

Fix gitless error

---

README.md

Hey! I've just created the [gitless-git](https://aur.archlinux.org/packages/gitless-git/) package for Arch Linux users to quickly grab and though it would be cool to note in the README. I've also obviously mentioned the non-upstream gitless package in the AUR, that already existed.
Thanks for this project! 🥺

add AUR packages to readme
